RF-916: Fix initial workflow for PII screen
RizeFinance/prototype-ui pull request #79
Opened 2021-12-06 19:10 UTC by KramerJeff

JIRA: https://gathering.atlassian.net/browse/RF-916

Fix initial workflow on PII screen so date of birth has proper
validation. Change masking package to formatStringByPattern due to
backspaces not being read if user entered more characters than needed
in a specific pattern.

QA - Check PII screen when setting up a new customer and ensure the phone number, date of birth, and social security number inputs are properly validating user input

2021-12-06 19:15 UTC, ksalmon requested changes
Go back and read the ticket's second requirement. We need to do a better job at handling the error if the PII PUT is not a proper request. For example if the SSN already exists in the program you will get an error

2021-12-07 14:56 UTC, RockinRonE requested changes

2021-12-07 14:56 UTC, RockinRonE commented on screens/PIIScreen.tsx
> +      .max(maxDob, 'You should be at least 18 years old.')
I'm able to add letters in the DOB field...while I get a validation error, should we prevent the user from doing so?

2021-12-07 14:56 UTC, RockinRonE commented on screens/PIIScreen.tsx
> +              <Dropdown
Let's have the background color, border, etc. to match the other inputs.

2021-12-08 14:24 UTC, ksalmon approved these changes

2021-12-13 22:14 UTC, ksalmon requested changes

2021-12-13 22:14 UTC, ksalmon commented on screens/ConfirmPIIScreen.tsx
> +          if (error[0]) {
What happens if there is more than one error? I would prefer it if we could concatenate and display them all.

2021-12-13 22:16 UTC, ksalmon requested changes

2021-12-13 22:16 UTC, ksalmon commented on screens/ConfirmPIIScreen.tsx
>          (error) => {
This makes sense to call it `errors`

2021-12-14 14:52 UTC, ksalmon approved these changes
LGTM

2021-12-14 16:10 UTC, RockinRonE commented on screens/PIIScreen.tsx
> +              <Dropdown
@ksalmon @KramerJeff I found if you move the input styles of the DropDown from `input` to `container` it at least styles the input.

Specifically moving: 
`
borderRadius: 4,
      borderColor: border,
      borderWidth: 2,
`
from input to container

🤷 about the placeholder

Up to you all how far you want to go, but this seemed easy enough

2021-12-14 16:10 UTC, RockinRonE approved these changes
Not gonna hold this up about styling, but I left a comment about some touchup that can be done

2021-12-14 16:44 UTC, merged