RF-790: Add conditional logic to transfers screen
RizeFinance/prototype-ui pull request #82
Opened 2021-12-30 16:58 UTC by RockinRonE

[Ticket](https://gathering.atlassian.net/browse/RF-790?atlOrigin=eyJpIjoiN2Y3YmVlMTJhNDVlNDBiYjgzNmFmZTljMzY5NWRmOGYiLCJwIjoiaiJ9)

I left the testData file for you all to check out. Just replace "account" with it within the account type check. 
<img width="631" alt="Screen Shot 2021-12-30 at 10 32 50 AM" src="https://user-images.githubusercontent.com/8163241/147772456-3352dc8a-0356-4fd8-96eb-3c95b399e74f.png">

2022-01-04 19:31 UTC, ksalmon approved these changes

2022-01-07 19:07 UTC, KramerJeff requested changes
Seeing the PR notification in Slack bothered me so I'm going to say request changes for the conflicts and because as far as I know, we're waiting on backend to implement some features still.

2022-01-18 21:15 UTC, ksalmon commented
@RockinRonE This work is now unblocked from this PR
https://github.com/RizeFinance/prototype-middleware/pull/65

2022-01-19 18:49 UTC, KramerJeff commented on screens/InitTransferScreen.tsx
> +                  &#8226; is NOT insured by the FDIC
Why are we making bullets like this? Shouldn't we be using CSS or a UL element?

2022-01-19 18:55 UTC, RockinRonE commented on screens/InitTransferScreen.tsx
> +                  &#8226; is NOT insured by the FDIC
@KramerJeff I know, I had the same question. Seems like RN doesn't do bullets. 

"React Native does not provide <ol> and <ul> like tags which auto handle bullet"

2022-01-19 18:56 UTC, KramerJeff approved these changes

2022-01-19 18:57 UTC, KramerJeff commented
Approved, no problems besides React Native being bogus about how they handle bullets

2022-01-19 18:58 UTC, merged