[RF-953] Target Yield Product
RizeFinance/prototype-ui pull request #85
Opened 2022-02-09 23:04 UTC by ksalmon

2022-02-17 21:09 UTC, RockinRonE requested changes
I haven't booted the app up yet, but I figured this maybe enough for now.

2022-02-17 21:09 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageOverviewScreen.tsx
> +      <Body>&nbsp;</Body>
You can always add some css instead of using this. If we ever need to compile this into an app, I'm not sure how devices will handle this spacing

2022-02-17 21:09 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProductQuestionsScreen.tsx
> +    const validationSchema = useMemo(() => {
This :)

2022-02-17 21:09 UTC, RockinRonE commented on screens/BrokerageOnboarding/OpenBrokerageButton.tsx
> +      title="Open Target Yeild Brokerage Account"
Typo in Yield

2022-02-18 19:34 UTC, ksalmon commented on contexts/BrokerageWorkflow.tsx
> +
Eh, I like types on the top. If anything we could move these to another scene types file

2022-02-18 19:35 UTC, ksalmon commented on contexts/BrokerageWorkflow.tsx
> +      find(workflows, { summary: { status: 'in_progress' } }) ||
I prefer the lodash syntax

2022-02-18 21:58 UTC, RockinRonE requested changes

2022-02-18 21:58 UTC, RockinRonE commented on screens/ConfirmPIIScreen.tsx
>  }: ConfirmPIIScreenProps): JSX.Element {
Can we add `loading` to the Confirm button?

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +    header: 'Complete your financial profile',
Each word needs to be capitalized

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProductQuestionsScreen.tsx
> +          <Input
<img width="486" alt="Screen Shot 2022-02-18 at 3 33 59 PM" src="https://user-images.githubusercontent.com/8163241/154764245-1d2ba5d8-9ef7-4913-b807-f5970783939b.png">

It would be cool if we could prevent letters and/or use a number mask to auto populate commas...I mean if there's time :)

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +        name: 'Are any of the account holders a control person of a publicly traded company? A Director, Officer or 10% stock owner?',
- "of the" isn't necessary

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +      },
Maybe "... a member of a firm, an exchange, FINRA, or a .... yadda yadda"

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProductQuestionsScreen.tsx
> +          <Input
Adding only a space causes the button to be enabled.

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +    header: 'Time Horizon and Liquidity Needs (When do I need my money?)',
Capitalize "when do I need my money"???

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +        name: 'Which of the following best describes my investment goal?',
"....describes YOUR investment goals...."

2022-02-18 21:58 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +      'Your risk temperament, or risk tolerance reflects your willingness to risk losing some or all of your original investment in an effort to achieve potentially higher returns. :',
` Your risk temperament, or risk tolerance reflects your willingness to risk losing some or all of your original investment in an effort to achieve potentially higher returns. :',`

- no need for a comma after "temperament"
- "in an effort to" => "to"
- I don't think you need the ":" at the end of this sentence

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProcessingScreen.tsx
> +          <Heading5 textAlign="center">
<img width="1425" alt="Screen Shot 2022-02-18 at 3 48 46 PM" src="https://user-images.githubusercontent.com/8163241/154766003-39202c6a-39a6-4d55-8aca-147938eae7fc.png">

Received this message but I'm unsure why

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProcessingScreen.tsx
> +          <Heading5 textAlign="center">
<img width="1715" alt="Screen Shot 2022-02-18 at 3 51 04 PM" src="https://user-images.githubusercontent.com/8163241/154766141-359d3739-ab2d-4b92-b976-f5f3bcbf0430.png">
And then this...

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/OpenBrokerageButton.tsx
> +      style={styles.button}
Correct here, but I saw this:
<img width="536" alt="Screen Shot 2022-02-18 at 3 52 03 PM" src="https://user-images.githubusercontent.com/8163241/154766324-183aa309-e4be-4c1e-9827-1d2ea69cba0b.png">

the "yield" part

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageProcessingScreen.tsx
> +          <Heading5 textAlign="center">
Went through the flow again and received the same error. Mind you I'm just putting in random values for the inputs.

2022-02-18 21:58 UTC, RockinRonE commented on screens/BrokerageOnboarding/BrokerageDisclosuresScreen.tsx
>  import { useNavigation } from '@react-navigation/native';
<img width="451" alt="Screen Shot 2022-02-18 at 3 57 09 PM" src="https://user-images.githubusercontent.com/8163241/154766789-4f30e38c-175e-4c2d-8b13-18dc7cdf9d6f.png">

Patriot Act is listed twice here

2022-02-22 17:40 UTC, ksalmon commented on screens/BrokerageOnboarding/BrokerageProductQuestionsScreen.tsx
> +          <Input
Let's leave this for now. I asked this question from product and I want them to get back to us first.
https://rizeup.slack.com/archives/C1XS8HJHF/p1645551511626069

2022-02-22 19:59 UTC, ksalmon commented on screens/ConfirmPIIScreen.tsx
>  }: ConfirmPIIScreenProps): JSX.Element {
Updated format of address display and added loading button

2022-02-22 20:00 UTC, ksalmon commented on screens/BrokerageOnboarding/BrokerageDisclosuresScreen.tsx
>  import { useNavigation } from '@react-navigation/native';
Yes, cause we acknowledge it twice. This is a display bug that is not relevant to this piece of work

2022-02-22 20:01 UTC, ksalmon commented on screens/BrokerageOnboarding/BrokerageProcessingScreen.tsx
> +          <Heading5 textAlign="center">
Ok, added some validation here

2022-02-22 20:28 UTC, ksalmon commented on screens/BrokerageOnboarding/BrokerageDisclosuresScreen.tsx
>  import { useNavigation } from '@react-navigation/native';
I fixed this in [this commit ](https://github.com/RizeFinance/prototype-ui/pull/85/commits/6593f74ba4f260563001cb88048adad2505ea19a)

2022-02-22 20:53 UTC, RockinRonE requested changes

2022-02-22 20:53 UTC, RockinRonE commented on screens/ConfirmPIIScreen.tsx
>        <Body>&nbsp;</Body>
Optional Middle Name is missing for confirmation.
<img width="552" alt="Screen Shot 2022-02-22 at 2 38 18 PM" src="https://user-images.githubusercontent.com/8163241/155216604-11adb960-3b1a-4884-8067-e78fac5b5034.png">

Do we care about the formatting of the phone number and birthdate?

Need to have a link so a user can revise their info if needed

2022-02-22 20:53 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +    header: 'Complete your financial profile',
This still needs to be capitalized....no? Just following the pattern for the other headers here.

2022-02-22 20:53 UTC, RockinRonE commented on constants/BrokerageSteps.ts
> +        pattern: '^([1-9]|10)$',
If I have no dependents (0) and enter that in, it disabled the button

2022-02-22 21:01 UTC, ksalmon commented on screens/ConfirmPIIScreen.tsx
>        <Body>&nbsp;</Body>
@RockinRonE We are skipping the revise info logic for now and I'm not worried about the formatting for existing data right now.

2022-02-22 21:04 UTC, RockinRonE approved these changes
Fiiiine, don't let me update my personal info :-p

2022-02-22 21:07 UTC, ksalmon commented
> Fiiiine, don't let me update my personal info :-p

Another ticket for another time. Right now we need to get this into live ENVs for our clients to see and for our teams to test.

2022-02-22 22:39 UTC, KramerJeff approved these changes
Overall, looks good to me. Saw a couple of `any` but they were for very generic objects anyway. I definitely can't verify all the functionality since this is a large set of work. @RockinRonE seems to have done a good job of testing basic edge cases.

2022-02-23 02:07 UTC, merged